<a href="https://colab.research.google.com/github/changlinli/cuda-colab-experiments/blob/main/Copy_of_gpu_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### References

Here are a few resources that might be helpful if you are stuck/confused at any point.

https://docs.nvidia.com/cuda/pdf/CUDA_C_Programming_Guide.pdf is the comprehensive guide to writing CUDA code and kernels. You can refer to this to figure out the documentation/signatures of functions.

https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/index.html is the documentation for NCCL (NVIDIA Collective Communication Library). Refer to this for documentation about inter-GPU communication. We are using a patched version of NCCL, which allows us to pretend we are using multiple GPUs while we have only one for testing and learning without having to actually get a multi-GPU setup.

### Before you start

If you are using google colab, ensure that you are connected to a GPU runtime by selecting Runtime -> Change runtime type -> Hardware accelerator -> GPU

Switch to [this notebook](https://colab.research.google.com/drive/1e1xO6c1GNGOcNRLuYd4SIuY45Fq7FYZl) for the python version of this notebook - it makes debugging a lot harder though, and overall gives you less control over the kernels you write.

### Caveats
- we will be using python files instead of jupyter notebooks because CUDA programs can cause process to hang and be unresponsive. If this happens, you can find the offending process' ID using `nvidia-smi` or `ps aux`, and terminate it with `kill -9 <pid>`.

## Adding two vectors (and toolchain setup)

We will start off with a simple kernel to add two 1D torch tensors. First, we need to write the kernel with C++, which will be compiled by nvcc, nvidia's C compiler. Let's call this `add_kernel.cu` (the next cell explains what's going on in more detail)

```cpp
#include <stdio.h>
extern "C" { // to prevent C++ name mangling, we use extern "C"
    __global__ void add_cuda_kernel(float *a, float *b, float *c, int size) {
        int i = threadIdx.x + blockIdx.x * blockDim.x;
        if (i < size) {
            c[i] = a[i] + b[i];
        }
    }

    void add_cuda(float *a, float *b, float *c, int size, cudaStream_t *stream) {
        dim3 blockDim(256);
        dim3 gridDim((size + blockDim.x - 1) / blockDim.x);
        add_cuda_kernel<<<gridDim, blockDim, 0, *stream>>>(a, b, c, size);
    }
}
```

We also need driver code to create tensors and call our kernel:
```python
import os

import torch
import ctypes
import subprocess

kernel_file = "add_kernel.cu"

# Compile the CUDA kernel using nvcc
nvcc_command = "nvcc -shared --compiler-options '-fPIC' -o kernel.so " + kernel_file + " -I /usr/include/torch/csrc/api/include/"
result = subprocess.run(nvcc_command, shell=True, text=True, capture_output=True)

if result.returncode != 0:
    print(f"Error: nvcc compilation failed")
    print(result.stderr.strip())
    exit(1)
else:
    print(f"compilation successful")

# Initialize CUDA variables
device = torch.device("cuda")
size = 1024

# Allocate and assign input tensors in GPU memory
a = torch.ones(size, device=device)
b = torch.ones(size, device=device)
c = torch.zeros(size, device=device)

# Load the custom kernel
lib = ctypes.CDLL(f"{os.getcwd()}/kernel.so")

# Define the argument types and return type for the function
lib.add_cuda.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_int, ctypes.POINTER(ctypes.c_void_p)]
lib.add_cuda.restype = None

stream = torch.cuda.current_stream()

print("calling our kernel...")
# Call the custom CUDA kernel
lib.add_cuda(a.data_ptr(), b.data_ptr(), c.data_ptr(), int(size), ctypes.c_void_p(stream.cuda_stream))

# Synchronize the CUDA stream
torch.cuda.synchronize()

# Print the result
print(c)

```

To run our kernel, we can now just run the python file. It will compile the kernel (with nvcc), load it, and call it. The output you see should be a bunch of twos, because 1 + 1 = 2. Try tweaking the code to have different input sizes.

Exercise: how would you add two, or multi dimensional tensors?

In [ ]:
!python driver.py

compilation successful
calling our kernel...
tensor([2., 2., 2.,  ..., 2., 2., 2.], device='cuda:0')


## Adding two vectors: explained
Here's what each line in our kernel does - most of this was written by GPT, which seems like a pretty good way to figure out what something is doing if you are confused. Look at [nvidia's documentation](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#c-language-extensions) for more detailed description of their C/C++ API.

### add_kernel.cu

`#include <stdio.h>`

The preprocessor directive #include tells the compiler to include the contents of the standard input/output header file (stdio.h) in the program. stdio.h allows us to use printf for debugging.

`extern "C" {`

This line specifies that the following functions should be treated as C functions, which are not name-mangled by the C++ compiler. This is important for interoperability between CUDA and other languages, such as calling CUDA kernels from Python using ctypes or similar mechanisms.

`__global__ void add_cuda_kernel(float *a, float *b, float *c, int size) {`

This line defines a CUDA kernel function named "add_cuda_kernel" with a \_\_global\_\_ attribute, meaning this function can be called from the host (CPU) and executed on the device (GPU). The function takes four parameters: three float pointers to our tensors a, b, and c, and an integer size.

`int i = threadIdx.x + blockIdx.x * blockDim.x;`

This line computes the current thread's index `i` based on the thread's x-coordinate `threadIdx.x` within a block, the block's x-coordinate `blockIdx.x` within the grid, and the block's size `blockDim.x` along the x-axis. This approach is used to handle one-dimensional array indexing in parallel.

`if (i < size) {`

This if statement checks if the current index `i` is within the bounds of the input array size.

`c[i] = a[i] + b[i];`

If the index is within bounds, this line performs an element-wise addition of the corresponding elements in arrays a and b and stores the result in array c.

`void add_cuda(float *a, float *b, float *c, int size, cudaStream_t *stream) {`

This line declares a C function called add_cuda that takes five parameters: three float pointers (a, b, and c), an integer (size), and a cudaStream_t pointer (stream).

`dim3 blockDim(256);`

This line creates a dim3 object called blockDim and initializes it with the dimensions (256, 1, 1) for the block. The block has 256 threads along the x-axis and a single thread along the y and z axes.

`dim3 gridDim((size + blockDim.x - 1) / blockDim.x);`

This line computes the grid dimensions, based on the input array size and block dimensions. It calculates the number of blocks, rounding up to cover the entire array by adding (blockDim.x - 1) before dividing.

`add_cuda_kernel<<<gridDim, blockDim, 0, *stream>>>(a, b, c, size);`

This line launches the add_cuda_kernel on the GPU with the specified grid and block dimensions, no shared memory (0), and the given stream. The kernel is passed the input parameters a, b, c, and size.

## Debugging (optional, set this up when you need it)
Before actually using a debugger, try logging stuff with `printf("%d\n", some_value)`. If you have segmentation faults, compile the kernel with libSegfault:
```python
nvcc_command = "nvcc -shared --compiler-options '-fPIC -lSegFault' -o kernel.so " + kernel_file + " -I /usr/include/torch/csrc/api/include/"
```
This should tell you where exactly your program is segfaulting.

### cuda-gdb

You can use `cuda-gdb` to attach a debugger to your program:

0. Modify the nvcc command in your python code to include debug symbols, disable optimization, and include lineinfo:
```python
nvcc_command = "nvcc -g -G -O0 -lineinfo -shared --compiler-options '-fPIC -lSegFault' -o kernel.so " + kernel_file + " -I /usr/include/torch/csrc/api/include/"
```

1. Launch `cuda-gdb`:
```
PYTHON_DISABLE_OPTIMIZE=1 cuda-gdb python
(gdb) set args path/to/your/python_script.py
```

2. Set a breakpoint in your CUDA kernel code by specifying the source file name and the line number:
```
(gdb) break your_cuda_source.cu:line_number
```
Replace `your_cuda_source.cu` and `line_number` with the actual file name and line number where you want to set the breakpoint (e.g., `break my_kernel.cu:99`). Make sure you set the breakpoint before running the Python script.

3. Run your Python script:
```
(gdb) run
```

4. `cuda-gdb` should now break at the specified line number in your CUDA kernel code. You can debug your kernel code using the various `gdb` commands:
- Step through the code with `next` (`n`) or `step` (`s`).
- Set breakpoints using `break` (`b`). For example, `break my_cuda_file.cu:123` sets a breakpoint at line 123 in `my_cuda_file.cu`.
- Examine variable values with `print` (`p`), such as `print array[0]`.
- Use `info cuda kernels` to display information about active kernels and their launches.
- Use `info cuda devices` to display information about CUDA devices.
- Use `info cuda loc` to show the current kernel location.

Remember that due to the asynchronous nature of CUDA kernels, you must [use breakpoints](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#breakpoint-function) explicitly in kernel code to pause execution at specific points.


## Syntactic Sugar

Loading the kernel, specifying the return types, getting the pointers to your data and calling the kernel, and synchronizing the stream can get annoying. So, if you'd like some syntactic sugar, you can run the cell below to get a decorator, `@kernel_function` that allows you to get away with simply specifying the function name and signature of your C++ function. So,
```python
# Load the custom kernel
lib = ctypes.CDLL(f"{os.getcwd()}/kernel.so")

# Define the argument types and return type for the function
lib.add_cuda.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_int, ctypes.POINTER(ctypes.c_void_p)]
lib.add_cuda.restype = None

stream = torch.cuda.current_stream()

print("calling our kernel...")
# Call the custom CUDA kernel
lib.add_cuda(a.data_ptr(), b.data_ptr(), c.data_ptr(), int(size), ctypes.c_void_p(stream.cuda_stream))

# Synchronize the CUDA stream
torch.cuda.synchronize()
```
can be written as
```python
@kernel_function(lib_path=f"{os.getcwd()}/kernel.so")
def sum_cuda(lib, a: Tensor, c: Tensor, size: int, stream: torch.cuda.streams.Stream) -> None:
    return lib.add_cuda

sum_cuda(a, c, size)
```

After this, every call to sum_cuda automatically does all the heavy-lifting for you.

In [ ]:
import requests
exec(requests.get('https://gist.githubusercontent.com/pranavgade20/c629d4134f5cc6998b489892b3f90a1b/raw/fb8dc248219c8a60e1cbe6079bdec8d7cfbc777a/kernel_function_decorator.py').text)

## Atomic Operations

Consider how you'd implement a kernel that sums all elements in a tensor - multiple threads writing to the same memory location can lead to race conditions. This is when multiple threads attempt to perform operations on some memory location, and different orders of operation can result in different results.

For example, consider two threads, A and B, attempting to increment a variable:
[![](https://mermaid.ink/img/pako:eNqFkTFrwzAQhf-KODAeGkO9Chqw6dIhSzNk0SKkaytandzLeQjG_72XiJbSEKpJvO_pnXi3QCgRwULTLImSWLO08oYZW9tGz-_tujaNI0dH_JyRAj4m_8o-OzJ6Js-SQpo8iRmupR3mwqdrfaxSxd12ezdY84w-mlBmEmTzYPr7v57xpmdQrAlPFFg_rvlSTN9XNiobb7ChU9jVCdYcOAn-Tv9J-M8FG8jI2aeoPS7nVw4uHTqwej3X6MDRqj4_S9mfKIAVnnED8xS9fHcK9sV_HFXFmKTwri7msp_1C1Uuhvw?type=png)](https://mermaid.live/edit#pako:eNqFkTFrwzAQhf-KODAeGkO9Chqw6dIhSzNk0SKkaytandzLeQjG_72XiJbSEKpJvO_pnXi3QCgRwULTLImSWLO08oYZW9tGz-_tujaNI0dH_JyRAj4m_8o-OzJ6Js-SQpo8iRmupR3mwqdrfaxSxd12ezdY84w-mlBmEmTzYPr7v57xpmdQrAlPFFg_rvlSTN9XNiobb7ChU9jVCdYcOAn-Tv9J-M8FG8jI2aeoPS7nVw4uHTqwej3X6MDRqj4_S9mfKIAVnnED8xS9fHcK9sV_HFXFmKTwri7msp_1C1Uuhvw)

Here, because B read before A had written the result back, B thinks counter = 10, when it should actually be 11. What we need is a way to make sure the operations are *atomic*. That is, no other threads can interrupt the operation in the middle of its execution.

CUDA has a few [atomic operations](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomic-functions), designed to prevent race conditions and maintain data integrity when multiple threads attempt to access or modify the same memory location simultaneously.

Implement a kernel that sums a tensor using the `atomicAdd` function.

In [ ]:
# Run this to setup the code

import os

import torch
import ctypes
import subprocess
import functools

kernel_file = "add_kernel.cu"

# Compile the CUDA kernel using nvcc
def create_nvcc_command(kernel_file_without_cu: str) -> str:
  kernel_file_cu = kernel_file_without_cu + ".cu"
  kernel_file_o = kernel_file_without_cu + ".o"
  return f"nvcc -shared --compiler-options '-fPIC' -o {kernel_file_o} {kernel_file_cu} -I /usr/include/torch/csrc/api/include/"

def compile_with_nvcc(kernel_file_without_cu: str):
  return subprocess.run(create_nvcc_command(kernel_file_without_cu), shell=True, text=True, capture_output=True)

compile_with_nvcc("add_kernel.cu")

# A nice little decorator to compile the program as well as run it
def make_kernel_function(kernel_file_without_cu: str):
  def decorator(f):
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
      print("hello_0")
      compile_with_nvcc(kernel_file_without_cu)
      print("hello")
      decorated = kernel_function(f"{os.getcwd()}/{kernel_file_without_cu + '.o'}")(f)
      return decorated
    return wrapper

# I'll deal with this later
# @make_kernel_function("add_kernel")
# def add_cuda(lib, a: torch.Tensor, c: torch.Tensor, size: int, stream: torch.cuda.streams.Stream) -> None:
    # return lib.add_cuda

In [ ]:
!python driver_tensor_sum.py

compilation successful
calling our kernel...
tensor([4096.], device='cuda:0')


In [ ]:
torch.ones(1024).size(dim=0)

1024

In [ ]:
import driver_tensor_sum

driver_tensor_sum.basic_tensor_sum(torch.ones(1024))

compilation successful
calling our kernel...
tensor([4096.], device='cuda:0')


tensor([1024.], device='cuda:0')

## Building a performance pyramid - divide and conquer

When building systems, user (and programmer) ease-of-use often needs to be traded off with performance. So, limiting the functionality in certain ways can often lead to performance boosts. As a performance engineer, you can use opportunities like this to improve your code's performance by processing the data in several passes using different APIs.

For example, consider the atomicAdd function we used above for calculating the sum of the tensor. Every thread has to acquire a lock to ensure that no other threads are in the middle of operating on the data, perform the operation, and then release the lock so that other threads can operate on the data. Accessing global memory is also often fairly slow, as it can not take advantage of [locality of reference](https://en.wikipedia.org/wiki/Locality_of_reference). So, a way to speed up your kernel is by using cached data. CUDA allows us to allocate and use shared memory, which threads in a thread block can read and write to. We will use shared memory to reduce the number of atomic additions we have to perform in the following section.

## Shared Memory

Read [this article](https://developer.nvidia.com/blog/using-shared-memory-cuda-cc/) on using shared memory in your CUDA kernels, and use static shared memory to read blocks of 256 (the maximum size of a thread block) elements from global memory. Then, reduce the elements following a pattern like this (you are starting with 256 elements instead of 8 in this illustration):

[![](https://mermaid.ink/img/pako:eNqF0lFrgzAQAOC_Eq5YO2hhJm3H8jBwtWvf28e8BE1XWY0ji2xD_O-NzYNBDSYvx_GR3B1XQ1pmAigEQZ3LXFNUh_oqChHSMOPqK2yaIGCSycut_E2vXGl0TphE5sTRIp7PXqP57I88m4A8odXqDcW4n7b83eHRNN85HHd8h_tpyxOHk2m-d_i643vcT1v-4fDNND84fNvxA-6nLT86_GWaDydmB0k8g8Sjg_TxYU-2VeJpFY-26uPDX20xa08xZLSYMd5eWEIhVMHzzCx03T7B4LHMDKgJ231mwGRjHK90efqXKVCtKrGE6jvjWiQ5_1S8AHrhtx_R3AFufrGG?type=png)](https://mermaid.live/edit#pako:eNqF0lFrgzAQAOC_Eq5YO2hhJm3H8jBwtWvf28e8BE1XWY0ji2xD_O-NzYNBDSYvx_GR3B1XQ1pmAigEQZ3LXFNUh_oqChHSMOPqK2yaIGCSycut_E2vXGl0TphE5sTRIp7PXqP57I88m4A8odXqDcW4n7b83eHRNN85HHd8h_tpyxOHk2m-d_i643vcT1v-4fDNND84fNvxA-6nLT86_GWaDydmB0k8g8Sjg_TxYU-2VeJpFY-26uPDX20xa08xZLSYMd5eWEIhVMHzzCx03T7B4LHMDKgJ231mwGRjHK90efqXKVCtKrGE6jvjWiQ5_1S8AHrhtx_R3AFufrGG)

So, you add the odd-numbered elements to the even-numbered ones in step one, call `__syncthreads();` to wait for all threads, and repeat for all even threads, and so on. Make sure you call `__syncthreads();` in all threads in the block - the kernel will halt for all threads to call `__syncthreads();` before continuing execution.

Advanced: use [memory fences](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#memory-synchronization-domains) instead of the `__syncthreads();` thread barrier. Think about why would memory fences work here instead of `__syncthreads();`

The first thread in all blocks can then write to the target using `atomicAdd`.

Bonus: how does this compare to all blocks writing to global memory that is 256 times smaller, and the driver code calling the same kernel until it has been reduced completely? Is the `atomicAdd` approach faster in some cases?

In [ ]:
!python driver_tensor_sum_tree_reduce.py

compilation successful
calling our kernel...
tensor([1.0240e+03, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00, 1.0000e+00,
        1.0000e+00], device='cuda:0')
b[0]=tensor(1024., device='cuda:0')
b[256]=tensor(1., device='cuda:0')
b[512]=tensor(1., device='cuda:0')
b[768]=tensor(1., device='cuda:0')


In [ ]:
import driver_tensor_sum_tree_reduce

driver_tensor_sum_tree_reduce.tree_tensor_sum(torch.ones(1024))

compilation successful
calling our kernel...
tensor([1.0240e+03, 1.0000e+00, 1.0000e+00,  ..., 1.0000e+00, 1.0000e+00,
        1.0000e+00], device='cuda:0')
b[0]=tensor(1024., device='cuda:0')
b[256]=tensor(1., device='cuda:0')
b[512]=tensor(1., device='cuda:0')
b[768]=tensor(1., device='cuda:0')


tensor([1024.], device='cuda:0')

## Advanced: Shuffling

[Shuffling](https://developer.nvidia.com/blog/faster-parallel-reductions-kepler/) lets you perform faster reductions - use this to calculate the sum in a warp before summing the thread block.

### Benchmarking your code

Here's a helper function that runs your code 10 times to warm it up, and then 100 times to calculate the mean and std of execution times.

Alternatively, you can use the %timeit magic. However, this does not let torch versions warm up, so you might bet weird results.

In [ ]:
import numpy as np
import time
import torch as t

def benchmark(fn):
    for _ in range(10):
        x = t.rand(256*256*256, device='cuda', dtype=t.float32)
        fn(x)

    times = []
    for _ in range(100):
        x = t.rand(256*256*256, device='cuda', dtype=t.float32)
        start = time.perf_counter_ns()
        fn(x)
        times.append(time.perf_counter_ns() - start)
    times = np.array(times, dtype=float)
    return f"{times.min()} ns; {times.max()} ns per invocation (min; max of 100 runs)"

In [ ]:
print(benchmark(lambda x: x.sum()))  # baseline
print(benchmark(lambda x: driver_tensor_sum.basic_tensor_sum(x)))
print(benchmark(lambda x: driver_tensor_sum_tree_reduce.tree_tensor_sum(x)))

11886.0 ns; 32381.0 ns per invocation (min; max of 100 runs)
33315464.0 ns; 35268894.0 ns per invocation (min; max of 100 runs)
2910779.0 ns; 10675611.0 ns per invocation (min; max of 100 runs)


### What's next

You can find pytorch's implementations of cuda kernels [here](https://github.com/search?q=repo%3Apytorch%2Fpytorch+path%3Acuda%2F*.cu&type=code). Try figuring out how they work, or writing your own implementations and comparing the performance difference certain optimizations make. You can also read the [nvidia blog](https://developer.nvidia.com/blog/search-posts/?q=CUDA+C%2B%2B) to find out API features and how to use them.

A fun kernel to implement is matrix multiplication - this forms the basis for a lot of operations in DL, and can be implemented in a bunch of different ways. A fun exercise is implementing the 4x4 matrix multiplication algorithm Deepmind's AlphaTensor found recently - it is currently the fastest known method of multiplying 4x4 tensors!